[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    # 3.0.10 is the first Cython release that supports the numpy 2 C API
    "Cython>=3.0.10",

    # Build against numpy 2.0 for ABI compatibility with both numpy 1.x and 2.x
    "numpy>=2.0,<3",
]

[tool.black]
line-length = 79

[tool.cibuildwheel]
manylinux-i686-image = "manylinux2010"
